build:

  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    php71:
      environment:
        php: 7.1
    php72:
      environment:
        php: 7.2

  environment:
    variables:
      ENV: 'ci'
    mysql: false
    postgresql: false
    redis: false
    rabbitmq: false
    php:
      ini:
        'date.timezone': 'Europe/Amsterdam'
    docker: true

  tests:
    override:
      -
        command: make coverage
        coverage:
          file: var/coverage.clover.xml
          format: php-clover
      -
        command: bash <(curl -s https://codecov.io/bash)

filter:
  paths:
    - "src/"
  dependency_paths:
    - "vendor/"

build_failure_conditions:
  - 'issues.new.exists'
  - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'

checks:
  php:
    code_rating: true
    duplication: true
